Update example settings and sample sheet
BIMSBbioinfo/pigx_sarscov2_ww pull request #124
Opened 2022-06-01 09:44 UTC by jonasfreimuth

This should help in quickly setting up an independent test run using the test data already provided with the pipeline.

2022-06-01 11:11 UTC, rekado requested changes

2022-06-01 11:11 UTC, rekado commented on etc/settings.yaml.in
> +  reads-dir: sample_data/reads
I think this is problematic, because this means that when a user runs the workflow without having specified the `reads-dir` (and all those other locations) the conventional locations won't work any more.

All the other pipelines use `reads` as the conventional location for reads, so running the workflow in a directory that contains `reads` will just work.

I think it's best not to enshrine the directory name `sample_data` in the defaults here.

2022-06-01 11:17 UTC, jonasfreimuth commented on etc/settings.yaml.in
> +  reads-dir: sample_data/reads
Will do, but could we then adjust the test dir of the pipeline to follow this convention?

2022-08-02 20:33 UTC, rekado commented
I believe what's missing here is a change to pigx_sars-cov-2/tests/settings.yaml as the test files have been moved but the locations in the settings file still refer to the old locations.

Other than that this looks good to me.

2022-08-03 08:25 UTC, jonasfreimuth commented
> I believe what's missing here is a change to pigx_sars-cov-2/tests/settings.yaml as the test files have been moved but the locations in the settings file still refer to the old locations.

Oh yes, that should have been obvious if I had tested it. Fixed now.

2022-08-03 08:26 UTC, merged