Dev miri
BIMSBbioinfo/pigx_sarscov2_ww pull request #7
Opened 2021-05-12 11:27 UTC by mirifax

this branch has basically nothing new anymore. Just one documentation file. The scripts should be the same as in main and if there a conflicts in snakefile they were just doodles, so can be removed.

2021-05-13 11:14 UTC, rekado requested changes
Hi Miriam,

since the total number of effective changes is relatively small I think it makes sense to squash the commits into one or two commits by doing an interactive rebase.

Please fix the conflicts by removing the markers that git inserted into the snakefile.py.

Could you please update your pull request?

2021-05-13 11:14 UTC, rekado commented on snakefile.py
> +<<<<<<< HEAD
Please rebase your changes and edit the commits that introduce these conflict markers.

2021-05-13 11:14 UTC, rekado commented on snakefile.py
> +>>>>>>> 30b24b2 (updated snakefile for krona and kraken rule)
Please remove this in the commit that added this confilct.

2021-05-13 11:14 UTC, rekado commented on documentation/prep_for_kraken_krona.md
> +*Bevore KronaTools can run there are also preparation steps. First load with Guix and then do the following*
Typo: "Before"

2021-05-13 11:14 UTC, rekado commented on scripts/Krona_report.Rmd
> +  sample_dir: '../../../../local/Projects/AAkalin_pathogenomics/Kraken2_results/'
It's better to remove this specific location.

2021-05-13 11:14 UTC, rekado commented on scripts/Krona_report.Rmd
> +library(htmltools)
uhm, crashes the html file?

2021-05-14 08:24 UTC, rekado requested changes

2021-05-14 08:24 UTC, rekado commented on .gitignore
> +
please remove the change to the .gitignore file.

2021-05-14 08:24 UTC, rekado commented on documentation/prep_for_kraken_krona.md
> +* (3) snakefile.py runs the renderSite() command to generate the website based on (1) and (2)
Markdown supports "1.", "2." etc.  It will turn that into an enumerated list.

2021-05-14 08:24 UTC, rekado commented on scripts/Kraken2-report.Rmd
> +```
please also remove this change, as it is non-functional.

2021-05-14 08:24 UTC, rekado commented on scripts/Krona_report.Rmd
> +date: "5/4/2021"
Not sure if we should keep author and date here.

2021-05-14 08:24 UTC, rekado commented on scripts/Krona_report.Rmd
> +htmltools::includeHTML(kronaFile)
I'm a bit confused about this.  Do I understand this correctly that all this report does is ... include an existing report?  Why generate this wrapper then when we could use the existing report directly?

2021-05-14 08:24 UTC, rekado commented on scripts/generateSiteFiles.R
> +}
As far as I can tell, this code is not actually used, or is it?  There is no PARAMS_TARGET_NAME anywhere to be found.

What is the intention here?

2021-05-14 08:24 UTC, rekado commented on scripts/generateSiteFiles.R
> +yaml::write_yaml(site_yml, file = file.path(siteDir, "_site.yml"))
Is this file used at all?

2021-05-14 08:24 UTC, rekado commented on scripts/run_Kraken2-report.R
You could remove all these changes as they are only non-functional whitespace changes.

2021-05-14 08:24 UTC, rekado commented on snakefile.py
> +#     shell: "Rscript {params.run_report} --reportFile={params.report_rmd} --coverage_file={input} --sample_name={wildcards.sample} --outFile={output} >> {log} 2>&1"
same here; you can remove this change as it only affects a trailing line break.

2021-05-14 09:42 UTC, mirifax commented on scripts/Krona_report.Rmd
> +library(htmltools)
deleted it now finally

2021-05-14 11:25 UTC, closed without merging